### PR TITLE
Make version check fail fast without internet

### PR DESCRIPTION
**Pull request by ewoutp**
This PR changes the automatic version check in 2 ways:

- It adds a 1 second timeout on the check. 
- It ignores all network errors during the version check.

When one of the above problems occurs, the version check is ignored. 
In `--verbose` mode the following message is given:

```
Latest version check failed because of a network issue.
Use `swarm version` to try again.
```

Note: When testing, make sure to do a `rm ~/.swarm/last_update_info` otherwise the version check is skipped.

### CODE REVIEW

**Comment by ewoutp** [comment]
@zeisss @marians RFR

**Comment by marians** [comment]
I like the implementation including the `--verbose` message. Didn't test. Shall I?

**Comment by ewoutp** [comment]
@marians Please do

**Comment by marians** [comment]
Ok, tested.

- `swarm info` now fails immediately with one line of error from the failed version check. I see no reason to completely break the command in our case. We should try to let the command do its job here, I wouldn't even bother about the version check here.

- `swarm version`: This completely fails, too. It doesn't even print the current version. I'd like it to print the current version and _in addition_ inform that the version check could not be performed.

Wh treat these commands differently? Because `swarm info` has a lot more purpose than checking the CLI version and if it's up to date, while for `swarm version` it is pretty much the main purpose.

**Comment by ewoutp** [comment]
I've changed `swarm info` and `swarm version` such that they also cope better with the lack of internet.

```
$ swarm info
Swarm CLI version:    0.25.0+git (version check failed)
API endpoint:         http://192.168.33.101:8080/v1/
API status:           reachable
Logged in as user:    tester
Current environment:  tester/dev
```

```
$ swarm version
swarm version 0.25.0+git, build 3bc78be0aa (version check failed)
```

**Comment by marians** [comment]
@ewoutp That's good!

Here is a last wording suggestion: Change `version check failed` to `check for latest version failed`.

**Comment by ewoutp** [comment]
Changed

**Comment by marians** [comment]
LGTM!

**Pull request merged**
