### PR TITLE
explicitly validate user given service definition

### PR DESCRIPTION
**Pull request by zyndiecate**
deps
- https://github.com/giantswarm/user-config/pull/79

### CODE REVIEW

**Comment by marians** [comment]
@zyndiecate Want to explain what this change is abuot? I'm always curious :)

**Comment by zyndiecate** [comment]
Your curiosity could have guided you to the linked PR's where things become clear. Anyway. Validating service definitions was always done in the unmarshaller of the service definition type. This is bad due to different reasons. We decided to remove the implicit validation of service definitions from the unmarshaller and call `Validate()` explicit where needed now.

**Comment by marians** [comment]
> Your curiosity could have guided you to the linked PR's where things become clear.

You bet I went there :) But things didn't become clearer for me. Thanks for the explanation.

**Comment by zyndiecate** [comment]
RFR @ewoutp

**Comment by ewoutp** [comment]
LGTM

**Pull request merged**
