### PR TITLE
Adding message for case that org already exists

### PR DESCRIPTION
**Pull request by marians**
Fixes https://github.com/giantswarm/cli/issues/351

Depends on:

- [ ] https://github.com/giantswarm/client-go/pull/85

Preview:

```
$ swarm org create marianstestorg
The organization 'marianstestorg' already exists.
```

### CODE REVIEW

**Comment by marians** [comment]
RFR @ewoutp or @zyndiecate

**Comment by ewoutp** [comment]
LGTM.
Do the int-tests need updates?

**Comment by marians** [comment]
Seems there is no int-test for `swarm org create`

**Comment by marians** [comment]
Yeah. I merged the Makefile change. :(

Will fix that in master.

**Pull request merged**
