### PR TITLE
Create support message/ticket from inside the CLI

### PR DESCRIPTION
**Pull request by luebken**
See https://github.com/giantswarm/cli/issues/170

### CODE REVIEW

**Comment by zyndiecate** [comment]
Calling again. Whats up with this? Maybe @JosephSalisbury wants to take over next?

**Comment by JosephSalisbury** [comment]
Is this a priority now, or do we just want to finish it off?

**Comment by luebken** [comment]
As this is in later this is currently no priority. But raising awareness is nice and we could discuss this in product planning. 

Please only start issues that are in the backlog.

**Comment by marians** [comment]
@luebken We only moved this from "tip" to "later" 3 days ago and wanted to get your confirmation that this is not a priority currently and it's not really work in progress. Confirmed now. All good :)

**Comment by marians** [comment]
Closing, as we no longer maintain this CLI.

**Pull request closed without merging**
