### PR TITLE
Fixed usage not showing help command

### PR DESCRIPTION
**Pull request by ewoutp**
Tests were broken after change in cobra, see https://github.com/spf13/cobra/commit/24b4b01ffae1d5d272e44cd4e0b1ae9e810f0831

These "fixes" have happened frequently (recently).
Do we want to pin cobra?

### CODE REVIEW

**Comment by ewoutp** [comment]
@denderello @zyndiecate RFR

**Comment by denderello** [comment]
Hm, it's indeed not the first time we see a BC break from this repo. Sadly the last "release" according to the README was in June 2014 and no tags are available. Let's pin I would say.

Apart from that. LGTM

**Comment by ewoutp** [comment]
I've pinned cobra, it pulls in a lot of other dependencies (also added).
Please have one more look

**Comment by denderello** [comment]
LGTM

**Pull request merged**
