### PR TITLE
update: Handling resource not found

### LINKED ISSUE #399: Providing the wrong component prints an unhelpful "Wrong Input." message
```
swarm update --strategy=hot-swap database/mysql
Updating component 'database/mysql' with version 'latest' and strategy 'hot-swap'...
Wrong Input.
```

Here, the user forgot that he has to provide the service-name besides the component name (so there is a service e.g. called `mysql` which has a component named `database/mysql`). Since no component could be found, the API returns `wrong input`. The message printed by the CLI could be more helpful here.

### PR DESCRIPTION
**Pull request by marians**
Fixes #399

Preview:

```
Updating component 'database/mysql' with version 'latest' and strategy 'hot-swap'…
Unknown component 'database/mysql'.
Please specify the component name in the format <service>/<component>.
See "swarm help update" for details.
```

### CODE REVIEW

**Comment by marians** [comment]
RFR @ewoutp or @zyndiecate

**Comment by ewoutp** [comment]
I don't like it that it leaves part of the spinner visible.

Otherwise LGTM

**Comment by marians** [comment]
> I don't like it that it leaves part of the spinner visible.

Good point. I changed the `\n` to a `\r`, so the remainders of the spinner are overwritten by the error message.

**Comment by marians** [comment]
I actually forgot to push the commit I was just talking about. Here it is: https://github.com/giantswarm/cli/pull/458

**Pull request merged**
