### PR TITLE
Adding active-tasks list to service status

### PR DESCRIPTION
**Pull request by ewoutp**

### CODE REVIEW

**Comment by ewoutp** [comment]
I've added the "active" tasks of a service in `swarm status <service>`.
It looks like this:

```
$ swarm status
Service busywait is starting

component  image           instanceid    created              status
box        busybox:latest  upoh6jpnxrqe  2015-09-24 09:26:01  starting

taskid            description          status
zldqdy3li1995mky  Start component box  pending
```

If there are no active tasks, it looks like this:
```
$ swarm status
Service busywait is up

component  image           instanceid    created              status
box        busybox:latest  upoh6jpnxrqe  2015-09-24 09:26:01  up

No active tasks.
```

@marians Please comment on this / talk about it

**Comment by ZeissS** [comment]
I like it :)

**Comment by marians** [comment]
@ewoutp To gather some information:
- Where is the `Start component box` description string coming from, and how does this look like in other cases?
- What other statuses are there besides `pending`?

**Comment by ewoutp** [comment]
> Where is the Start component box description string coming from

that is being generated in the app-service. E.g. see https://github.com/giantswarm/app-service/pull/465/files#diff-7dad4614023247906df60281018c1cfbR79

> how does this look like in other cases?

Don't know yet, we only implemented the very first async task yet.

> What other statuses are there besides pending?

`in-progress` & `finished`.

Note that in the service status you won't see finished, because `finished` is not part of `active` tasks.

**Comment by ewoutp** [comment]
Right now this PR is intended for helping me build the task stuff, not to be merged into master before @marians has finished hish design for this stuff.

**Comment by zyndiecate** [comment]
> Right now this PR is intended for helping me build the task stuff, not to be merged into master

+1

**Comment by ewoutp** [comment]
This feature is now also available in `swarmctl` so I'm closing this PR waiting for UI thoughts on showing tasks to users.

**Pull request closed without merging**
