### PR TITLE
scaleup/scaledown: Handling resource not found error

### LINKED ISSUE #455: `swarm scaleup/down` should handle resource not found error with a helpful error message
Seems we are no longer printing our verbose error message for the case that the component name is misspelled.

```
swarm scaledown foo/wevserver/nginx 1
Scaling down component 'foo/wevserver/nginx' by 1…
Not found.
```

### PR DESCRIPTION
**Pull request by marians**
Fixes #455 

Preview:

```
Scaling down component 'foo/webserver/nginxs' by 1…
Unknown component 'foo/webserver/nginxs'.
Please specify the component name in the format <service>/<component>.
See "swarm help scaledown" for details.
```

### CODE REVIEW

**Comment by marians** [comment]
RFR @ewoutp @zyndiecate

**Comment by zyndiecate** [comment]
LGTM

**Comment by ewoutp** [comment]
LGTM

**Comment by marians** [comment]
That war QUICK! Thanks!

**Pull request merged**
