### PR TITLE
handle 'resource down' error on exec command

### PR DESCRIPTION
**Pull request by zyndiecate**
fixes https://github.com/giantswarm/cli/issues/476

deps
- https://github.com/giantswarm/hijack-stream-support/pull/4
- https://github.com/giantswarm/client-go/pull/89
- https://github.com/giantswarm/api/pull/197
- https://github.com/giantswarm/app-service/pull/557

The problem we have here is that there is no nice way to fetch information of an instance groups state when we hijack connections. I played around and opted for checking the instance group state before initializing any streaming connection. To be able to check eventual error responses, it was necessary to extend the hijacking library with an error handler. Please see https://github.com/giantswarm/cli/pull/488 and its dependencies. 

On my local machine we now see this.
```bash
# normal mode
$ swarm --api-endpoint=http://192.168.33.101:8080/v1/ exec 1iss2rmrx091 -- ps -a
Error: 'swarm exec' requires an instance to be up. Instance '1iss2rmrx091' is down.

# detached
$ swarm --api-endpoint=http://192.168.33.101:8080/v1/ exec --detach 1iss2rmrx091 -- ps -a
Error: 'swarm exec' requires an instance to be up. Instance '1iss2rmrx091' is down.
```

### CODE REVIEW

**Comment by zyndiecate** [comment]
RFR @ewoutp @ZeissS

**Comment by marians** [comment]
As an alternative, how about checking the instance state only if the response was empty? If there is a non-empty response, we don't really need to check. And an extra status check costs at least a few hundred ms on the user side.

**Comment by zyndiecate** [comment]
I prefer to have the status check before in general. Who knows for whatever reason the response can be empty. Feels error prone this way.

**Comment by ewoutp** [comment]
I agree with @zyndiecate, there should be a proper error check and not something implicitly.
Even if that costs a bit of performance (let's make fleet faster)

**Comment by zyndiecate** [comment]
Fishing for LGTM

**Comment by ewoutp** [comment]
LGTM

**Pull request merged**
