### PR TITLE
Clarify error when parsing swarmvars.json fails

### LINKED ISSUE #388: `swarm` exits if `swarmvars.json` file is empty
I'm getting an empty response from `swarm` if there is a `swarmvars.json` file that is empty in the same directory.  Steps to reproduce:

```
touch swarmvars.json
swarm up
```

### PR DESCRIPTION
**Pull request by ewoutp**
Putting an empty `swarmvars.json` in a folder broke `swarm up` without proper feedback.
This change adds better feedback.

New output:
```
$ touch swarmvars.json
$ swarm up
Cannot parse variables: unexpected end of JSON input
```

fixes #388

### CODE REVIEW

**Comment by ewoutp** [comment]
@denderello @kordless  RFR

**Comment by marians** [comment]
How about this little enahncement, to make it even more clear where to look? It might be that users aren't even aware that they have a swarmvars.json file.

```
$ touch swarmvars.json
$ swarm up
Cannot parse variables file 'swarmvars.json': unexpected end of JSON input
```

**Comment by ewoutp** [comment]
I've changed it according to the above "spec".

Note that the same function is also used to parse variables passed via the command line.
If that results in an error, the erro message remains:
```
Cannot parse variables: unexpected end of JSON input
```

**Comment by ewoutp** [comment]
Chances of that happening is really small...

**Comment by marians** [comment]
> Note that the same function is also used to parse variables passed via the command line.

Then "unexpected end of JSON input" is more related to the combined result of service definition and variables, right? Since the variables themselves aren't JSON.

**Comment by ewoutp** [comment]
It took me a while, but I found a way to trigger it (without a swarmvars.json)

```
$ swarm up --var "foo=\""
Cannot parse variables: invalid character '"' after object key:value pair
```

**Comment by marians** [comment]
LGTM

**Pull request merged**
