### PR TITLE
Terminal color output

### PR DESCRIPTION
**Pull request by Nesurion**
Enable colorful output in the cli. ie: `swarm status` the status of the service and the components will be highlighted based on there state (up, starting, failed, ...)

See #49

### CODE REVIEW

**Comment by Nesurion** [comment]
This is WIP but `status` and `start` are now colorful to some extend, not all return messages are styled just yet.

**Comment by marians** [comment]
Looking at the code, I am wondering: Wouldn't it be cleaner if the `if isTerminal ... else` distinction would happen inside the functions like `colorError`, `colorSuccess` etc?

**Comment by marians** [comment]
@Nesurion Did you already apply the highlight formatting on the column headers? I still see normal text there.

image

**Comment by Nesurion** [comment]
@marians and I discussed this. I'll write a print function that will encapsule the `isTerminal` selection. In terms of columns, I'll fork the `github.com/ryanuber/columnize` repo and exclude ansi escape codes from the counting routine.

**Comment by marians** [comment]
No longer relevant

**Pull request closed without merging**
