### PR TITLE
Improved 'swarm up' usage

### PR DESCRIPTION
**Pull request by marians**
This change should improve the usage notes as printed by `swarm help up`. See #390.

```
Create and start a new service from a service definition JSON file

Usage: 
  swarm up [<filepath>] [flags]

Docs:
  https://docs.giantswarm.io/reference/cli/up/

Examples:
  swarm up                                    Create and start service using swarm.json in the current directory
  swarm up <filepath>                         Create and start service using the given service definition file
  swarm up [<filepath>] --var-file=<filepath> Create and start service using var-file. Variables grouped by env's in var-file, that defaults to swarmvars.json
  swarm up [<filepath>] --var=<key=value>     Create and start service using variables. The given key, used as $key in swarm.json, will be replaced with the given value.

Flags:
  -d, --detach[=false]: Do not wait for the service to be started
  -n, --name="": Name used for the newly created service
      --var=[]: Key-Value variable pair, used in swarm.json
      --var-file="": Path to a file containing key-value variable pairs, used in swarm.json

Global Flags:
      --api-endpoint="https://api.giantswarm.io/v1": The API endpoint to talk to
      --config-dir="": Change the default configuration directory
      --debug[=false]: Log debug output or not
      --env="giantswarm/testing": Which environment to use. Format: 'organization/environment'
  -q, --quiet[=false]: Suppress output
  -v, --verbose[=false]: Verbose output
```

### CODE REVIEW

**Comment by marians** [comment]
Ping @teemow RFR

**Comment by teemow** [comment]
LGTM

**Comment by marians** [comment]
FYI: With this change, the string "swarm " is prepended to examples, which should make them much easier to understand. This has to be changed consistently for other commands. I'll do that in a different PR.

**Comment by ewoutp** [comment]
Next time please update the int-tests.

**Pull request merged**
