### PR TITLE
Prevent version check on dump terminals

### LINKED ISSUE #412: New version notice should only appear when STDOUT is an interactive terminal
To prevent the "A new CLI version is available" notice from appearing in a script environment, we should check if the current STDOUT is an interactive terminal.

Ping @luebken

### PR DESCRIPTION
**Pull request by ewoutp**
fixes #412  

When running the swarm command on a dumb terminal, the version check is skipped.

### CODE REVIEW

**Comment by ewoutp** [comment]
@marians @zyndiecate RFR

**Comment by zyndiecate** [comment]
How to test this?

**Comment by ewoutp** [comment]
Change `VERSION` to something lower then it is now, then compile and run.

```
rm ~/.swarm/last_update_info
swarm ls
```

This should show the version notice 

```
rm ~/.swarm/last_update_info
swarm ls | cat
```

This should not show the warning

**Comment by zyndiecate** [comment]
WFM

**Comment by marians** [comment]
LGTM

**Pull request merged**
