### PR TITLE
Update component async

### PR DESCRIPTION
**Pull request by zyndiecate**
epic giantswarm/giantswarm#242

deps
- https://github.com/giantswarm/app-service/pull/563
- https://github.com/giantswarm/api/pull/188
- https://github.com/giantswarm/app-client-go/pull/60
- https://github.com/giantswarm/client-go/pull/82

### CODE REVIEW

**Comment by ewoutp** [comment]
LGTM + WFM

**Comment by marians** [comment]
Is this really WIP?

**Comment by marians** [comment]
:8ball:

@zyndiecate Please add an entry in https://github.com/giantswarm/cli/wiki. Thanks!

**Comment by marians** [comment]
I currently can't get `swarm update` with a component to work. Trying it with alpha-aws.

```
[marian:~/git/cli] master+ 1 ± swarm status update-test
Service 'update-test' is up

component  image                instanceid    created              status
mysql      mysql:5.5            4u9vnb91q31a  2015-11-04 12:33:06  up
wordpress  wordpress:4.3.1-fpm  galgrtnyumvp  2015-11-04 12:33:05  up
```

```
[marian:~/git/cli] master+ 5s ± swarm update update-test/wordpress
Updating component 'update-test/wordpress' with version 'latest' and strategy 'one-by-one'…
Unknown component 'update-test/wordpress'.
Please specify the component name in the format <service>/<component>.
See "swarm help update" for details.
```

**Comment by zyndiecate** [comment]
Added wiki note.

**Comment by zyndiecate** [comment]
The issue you found is fixed when the api and appd is deployed.

**Pull request merged**
