### PR TITLE
Fixed build after docker change

### PR DESCRIPTION
**Pull request by ewoutp**
This PR updates a docker dependency and make the appropriate cod change to make the build succeed.

These docker changes are pretty frequent, so vendoring that code would be a better (future) alternative.

### CODE REVIEW

**Comment by ewoutp** [comment]
@zeisss RFR

**Comment by zeisss** [comment]
I think that's actually a nice change in docker. It's the same pattern we have.

**Comment by zeisss** [comment]
PS: We could now replace our docker client in appd with that client too, right?

**Comment by ewoutp** [comment]
The reason we import the docker stuff in the first place is to update the local docker configuration file with authentication stuff for our registry. As far as I can tell this is not in engine-api.

For other projects we can likely our docker client with this one.

**Pull request merged**
